version: "3.9"

services:
  mariadb-core:
    image: mariadb:11.4
    container_name: banquito-core-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: banquito_core
      MARIADB_USER: banquito
      MARIADB_PASSWORD: banquito123
    ports:
      - "3306:3306"
    volumes:
      - banquito_core_data:/var/lib/mysql
      - ./src/main/resources/modeloFisicoBD_Core_v5_mariadb.sql:/docker-entrypoint-initdb.d/01_core.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  banquito_core_data: