spring.application.name=banquito-core
server.port=8081

# ===============================
# CARGAR VARIABLES DESDE .env
# ===============================
spring.config.import=optional:file:.env[.properties]

# ===============================
# BASE DE DATOS - MariaDB Desplegada
# ===============================
spring.datasource.url=jdbc:mariadb://34.27.240.236:3306/banquito_core?useUnicode=true&characterEncoding=utf8
spring.datasource.username=admin
spring.datasource.password=banbanquito2
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Respeta nombres fisicos exactos del modelo SQL: CLIENTE, CUENTA, AUDITORIA_EVENTO, etc.
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# ===============================
# JSON
# ===============================
spring.jackson.default-property-inclusion=non_null

# ===============================
# LOGS SQL - Desarrollo
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# ACTUATOR - Monitoreo desarrollo
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,mappings
management.endpoint.health.show-details=always