-- ============================================================================
-- BANCO BANQUITO - CORE DE CUENTAS
-- Modelo físico relacional en MariaDB
-- Versión: 1.3 complementada - mejoras aditivas JPA, concurrencia y trazabilidad
-- Fecha: Abril 2026
--
-- Criterio de diseño:
-- - Base conceptual: core_model.sql del Ing. del proyecto.
-- - Nomenclatura: tablas y campos en español, sin tildes para compatibilidad SQL.
-- - Motor: MariaDB / InnoDB.
-- - Objetivo: cumplir Core de Cuentas, soporte al Switch de Pagos Masivos,
--   trazabilidad, integridad, seguridad básica, buena normalización y mapeo JPA profesional.
-- - Versión 1.3: solo agrega mejoras aditivas; no elimina ni renombra estructuras funcionales.
-- ============================================================================

CREATE DATABASE IF NOT EXISTS banquito_core
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE banquito_core;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS AUDITORIA_EVENTO;
DROP TABLE IF EXISTS HISTORIAL_ESTADO_CUENTA;
DROP TABLE IF EXISTS BLOQUEO_CUENTA;
DROP TABLE IF EXISTS TRANSACCION_INSTITUCIONAL;
DROP TABLE IF EXISTS TRANSACCION_CUENTA;
DROP TABLE IF EXISTS SUBTIPO_TRANSACCION;
DROP TABLE IF EXISTS CUENTA_INSTITUCIONAL;
DROP TABLE IF EXISTS CUENTA;
DROP TABLE IF EXISTS SUBTIPO_CUENTA;
DROP TABLE IF EXISTS USUARIO_CORE;
DROP TABLE IF EXISTS CREDENCIAL_WEB;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SUBTIPO_CLIENTE;
DROP TABLE IF EXISTS PARAMETRO_CORE;
DROP TABLE IF EXISTS FERIADO;
DROP TABLE IF EXISTS SUCURSAL;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- 1. DOMINIO DE SUCURSALES, PARAMETROS Y CALENDARIO
-- ============================================================================

CREATE TABLE SUCURSAL (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico de la sucursal',
    CODIGO_SUCURSAL VARCHAR(10) NOT NULL COMMENT 'Codigo alfanumerico unico de la sucursal',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre comercial de la sucursal',
    CIUDAD VARCHAR(80) NOT NULL COMMENT 'Ciudad donde opera la sucursal',
    DIRECCION VARCHAR(300) NULL COMMENT 'Direccion fisica de la sucursal',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA' COMMENT 'Estado operativo de la sucursal',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del registro',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del registro',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de sucursales del banco';

CREATE TABLE FERIADO (
    FECHA_FERIADO DATE NOT NULL COMMENT 'Fecha exacta del feriado o dia no habil',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre o motivo del feriado',
    ES_FIN_SEMANA TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=fin de semana, 0=feriado configurado',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado de la configuracion',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de configuracion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del feriado',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_FERIADO PRIMARY KEY (FECHA_FERIADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Calendario de dias no habiles consultable por Core y Switch';

CREATE TABLE PARAMETRO_CORE (
    CODIGO VARCHAR(50) NOT NULL COMMENT 'Codigo unico del parametro, ejemplo IVA_PORCENTAJE',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre legible del parametro',
    VALOR_TEXTO VARCHAR(255) NOT NULL COMMENT 'Valor almacenado como texto para conversion por aplicacion',
    TIPO_DATO VARCHAR(20) NOT NULL COMMENT 'Tipo real del dato: NUMERICO, CADENA, FECHA, HORA, BOOLEANO',
    DESCRIPCION VARCHAR(255) NULL COMMENT 'Descripcion funcional del parametro',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima modificacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_PARAMETRO_CORE PRIMARY KEY (CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Parametros dinamicos del Core Bancario';

-- ============================================================================
-- 2. DOMINIO DE CLIENTES
-- ============================================================================

CREATE TABLE SUBTIPO_CLIENTE (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico del subtipo de cliente',
    TIPO_CLIENTE VARCHAR(15) NOT NULL COMMENT 'Tipo de cliente al que aplica el subtipo: NATURAL o JURIDICO',
    CODIGO VARCHAR(20) NOT NULL COMMENT 'Codigo funcional del segmento',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre comercial del segmento',
    DESCRIPCION VARCHAR(255) NULL COMMENT 'Descripcion de las caracteristicas del segmento',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del subtipo',
    OBSERVACIONES VARCHAR(255) NULL COMMENT 'Notas internas del segmento',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del subtipo de cliente',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_SUBTIPO_CLIENTE PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo para segmentacion comercial de clientes';

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico del cliente',
    SUBTIPO_CLIENTE_ID INT NOT NULL COMMENT 'Segmento comercial del cliente',
    TIPO_CLIENTE VARCHAR(15) NOT NULL COMMENT 'NATURAL o JURIDICO',
    TIPO_IDENTIFICACION VARCHAR(15) NOT NULL COMMENT 'CEDULA, RUC o PASAPORTE',
    IDENTIFICACION VARCHAR(20) NOT NULL COMMENT 'Numero del documento de identidad',
    NOMBRES VARCHAR(100) NULL COMMENT 'Nombres del cliente natural',
    APELLIDOS VARCHAR(100) NULL COMMENT 'Apellidos del cliente natural',
    RAZON_SOCIAL VARCHAR(150) NULL COMMENT 'Razon social del cliente juridico',
    FECHA_NACIMIENTO DATE NULL COMMENT 'Fecha de nacimiento para persona natural',
    FECHA_CONSTITUCION DATE NULL COMMENT 'Fecha de constitucion para persona juridica',
    REPRESENTANTE_LEGAL_ID INT NULL COMMENT 'Cliente natural representante legal de una persona juridica',
    EMAIL VARCHAR(100) NOT NULL COMMENT 'Correo electronico principal',
    TELEFONO_MOVIL VARCHAR(20) NOT NULL COMMENT 'Telefono movil principal',
    DIRECCION VARCHAR(255) NOT NULL COMMENT 'Direccion fisica principal',
    LATITUD DECIMAL(10,8) NULL COMMENT 'Latitud geografica',
    LONGITUD DECIMAL(11,8) NULL COMMENT 'Longitud geografica',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del cliente',
    ACTIVO_PAGOS_MASIVOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Indica si el cliente juridico tiene habilitado el servicio de pagos masivos',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de registro del cliente',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del cliente',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Titulares de productos bancarios: personas naturales y juridicas';

-- ============================================================================
-- 3. SEGURIDAD BASICA: CLIENTES WEB Y USUARIOS INTERNOS
-- ============================================================================

CREATE TABLE CREDENCIAL_WEB (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico de la credencial web',
    CLIENTE_ID INT NOT NULL COMMENT 'Cliente propietario de la credencial',
    USUARIO VARCHAR(50) NOT NULL COMMENT 'Usuario para Banca Web Empresas',
    PASSWORD_HASH VARCHAR(255) NOT NULL COMMENT 'Hash de la contrasena',
    ULTIMO_LOGIN DATETIME NULL COMMENT 'Ultimo acceso exitoso',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado de la credencial',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion de credencial',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_CREDENCIAL_WEB PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Credenciales de clientes para Banca Web Empresas';

CREATE TABLE USUARIO_CORE (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del usuario interno del banco',
    SUCURSAL_ID INT NULL COMMENT 'Sucursal asociada, obligatoria para roles de agencia',
    USUARIO VARCHAR(50) NOT NULL COMMENT 'Usuario interno del banco',
    PASSWORD_HASH VARCHAR(255) NOT NULL COMMENT 'Hash de la contrasena',
    NOMBRE_COMPLETO VARCHAR(150) NOT NULL COMMENT 'Nombre completo del empleado',
    ROL VARCHAR(50) NOT NULL COMMENT 'Rol administrativo',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del usuario',
    ULTIMO_LOGIN DATETIME NULL COMMENT 'Ultimo acceso al Core',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_USUARIO_CORE PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Usuarios administrativos internos del Core Bancario';

-- ============================================================================
-- 4. DOMINIO DE CUENTAS DE CLIENTE E INTERNAS
-- ============================================================================

CREATE TABLE SUBTIPO_CUENTA (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del producto pasivo',
    TIPO_BASE VARCHAR(15) NOT NULL COMMENT 'Naturaleza base: AHORROS o CORRIENTE',
    CODIGO VARCHAR(20) NOT NULL COMMENT 'Codigo unico del producto',
    NOMBRE VARCHAR(80) NOT NULL COMMENT 'Nombre comercial del producto',
    DESCRIPCION VARCHAR(255) NULL COMMENT 'Descripcion del producto',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado de comercializacion',
    OBSERVACIONES VARCHAR(255) NULL COMMENT 'Reglas u observaciones del producto',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del subtipo de cuenta',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_SUBTIPO_CUENTA PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de productos pasivos ofrecidos por el banco';

CREATE TABLE CUENTA (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico de la cuenta',
    NUMERO_CUENTA VARCHAR(20) NOT NULL COMMENT 'Numero de cuenta bancaria',
    CLIENTE_ID INT NOT NULL COMMENT 'Titular legal de la cuenta',
    SUCURSAL_ID INT NOT NULL COMMENT 'Sucursal de apertura',
    SUBTIPO_CUENTA_ID INT NOT NULL COMMENT 'Producto contratado',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA' COMMENT 'Estado operativo de la cuenta',
    SALDO_CONTABLE DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT 'Saldo real contable de la cuenta',
    SALDO_DISPONIBLE DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT 'Saldo utilizable, considerando bloqueos y reglas',
    PERMITE_SOBREGIRO TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Permite sobregiro controlado para casos autorizados',
    LIMITE_SOBREGIRO DECIMAL(19,2) NOT NULL DEFAULT 0.00 COMMENT 'Limite maximo de sobregiro permitido',
    ES_FAVORITA_PAGOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Cuenta favorita para pagos masivos por SFTP',
    FECHA_APERTURA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de apertura',
    FECHA_ULTIMO_MOVIMIENTO DATETIME NULL COMMENT 'Fecha del ultimo movimiento financiero',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_CUENTA PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cuentas pasivas pertenecientes a clientes del banco';

CREATE TABLE CUENTA_INSTITUCIONAL (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador de cuenta interna del banco',
    NUMERO_CUENTA VARCHAR(20) NOT NULL COMMENT 'Numero o codigo interno contable',
    CODIGO VARCHAR(50) NOT NULL COMMENT 'Codigo funcional, ejemplo INGRESOS_SERVICIOS_MASIVOS',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre de la cuenta institucional',
    TIPO_CUENTA VARCHAR(20) NOT NULL COMMENT 'INGRESO, PASIVO, IMPUESTO u OPERATIVA',
    SALDO_CONTABLE DECIMAL(19,2) NOT NULL DEFAULT 0.0000 COMMENT 'Saldo acumulado interno',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA' COMMENT 'Estado de la cuenta interna',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_CUENTA_INSTITUCIONAL PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cuentas internas del banco para ingresos, impuestos y otros conceptos';

-- ============================================================================
-- 5. DOMINIO TRANSACCIONAL
-- ============================================================================

CREATE TABLE SUBTIPO_TRANSACCION (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del subtipo de transaccion',
    CODIGO VARCHAR(30) NOT NULL COMMENT 'Codigo funcional del subtipo',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre descriptivo del movimiento',
    TIPO_MOVIMIENTO_BASE VARCHAR(15) NULL COMMENT 'DEBITO o CREDITO si el subtipo aplica a uno en particular',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del subtipo',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del subtipo de transaccion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_SUBTIPO_TRANSACCION PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo dinamico de conceptos de movimientos financieros';

CREATE TABLE TRANSACCION_CUENTA (
    ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico del movimiento de cuenta de cliente',
    CUENTA_ID INT NOT NULL COMMENT 'Cuenta de cliente afectada',
    SUBTIPO_TRANSACCION_ID INT NOT NULL COMMENT 'Concepto del movimiento',
    UUID_TRANSACCION CHAR(36) NOT NULL COMMENT 'Llave de idempotencia enviada por canal o Switch',
    UUID_GRUPO_OPERACION CHAR(36) NULL COMMENT 'Agrupador de operacion para debito/credito relacionados',
    FECHA_NEGOCIO DATE NOT NULL COMMENT 'Fecha contable o fecha de negocio de la transaccion',
    TIPO_MOVIMIENTO VARCHAR(15) NOT NULL COMMENT 'DEBITO o CREDITO',
    MONTO DECIMAL(19,2) NOT NULL COMMENT 'Valor del movimiento',
    SALDO_RESULTANTE DECIMAL(19,2) NOT NULL COMMENT 'Saldo contable posterior al movimiento',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'COMPLETADA' COMMENT 'Estado del movimiento',
    CANAL_ORIGEN VARCHAR(20) NOT NULL DEFAULT 'CORE' COMMENT 'Canal origen: CORE, AGENCIA, WEB, SWITCH, ATM, SISTEMA',
    REFERENCIA_EXTERNA VARCHAR(100) NULL COMMENT 'Referencia externa, archivo, lote o linea de Switch',
    DESCRIPCION VARCHAR(500) NULL COMMENT 'Descripcion o concepto de la transaccion',
    USUARIO_CORE_ID INT NULL COMMENT 'Usuario interno ejecutor si aplica',
    CREDENCIAL_WEB_ID INT NULL COMMENT 'Credencial web ejecutora si aplica',
    FECHA_TRANSACCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora real del movimiento',
    NUMERO_COMPROBANTE VARCHAR(20) NULL COMMENT 'Numero de comprobante o voucher',
    CONSTRAINT PK_TRANSACCION_CUENTA PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bitacora inmutable de movimientos financieros sobre cuentas de clientes';

CREATE TABLE TRANSACCION_INSTITUCIONAL (
    ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador unico del movimiento institucional',
    CUENTA_INSTITUCIONAL_ID INT NOT NULL COMMENT 'Cuenta interna del banco afectada',
    SUBTIPO_TRANSACCION_ID INT NOT NULL COMMENT 'Concepto del movimiento',
    UUID_TRANSACCION CHAR(36) NOT NULL COMMENT 'Llave de idempotencia del movimiento institucional',
    UUID_GRUPO_OPERACION CHAR(36) NULL COMMENT 'Agrupador con operaciones relacionadas',
    FECHA_NEGOCIO DATE NOT NULL COMMENT 'Fecha contable o fecha de negocio',
    TIPO_MOVIMIENTO VARCHAR(15) NOT NULL COMMENT 'DEBITO o CREDITO',
    MONTO DECIMAL(19,2) NOT NULL COMMENT 'Valor del movimiento',
    SALDO_RESULTANTE DECIMAL(19,2) NOT NULL COMMENT 'Saldo contable posterior',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'COMPLETADA' COMMENT 'Estado del movimiento',
    CANAL_ORIGEN VARCHAR(20) NOT NULL DEFAULT 'SISTEMA' COMMENT 'Canal origen',
    REFERENCIA_EXTERNA VARCHAR(100) NULL COMMENT 'Referencia externa, archivo, lote o linea de Switch',
    DESCRIPCION VARCHAR(500) NULL COMMENT 'Descripcion del movimiento interno',
    USUARIO_CORE_ID INT NULL COMMENT 'Usuario interno ejecutor si aplica',
    CREDENCIAL_WEB_ID INT NULL COMMENT 'Credencial web ejecutora si aplica',
    FECHA_TRANSACCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora real del movimiento',
    CONSTRAINT PK_TRANSACCION_INSTITUCIONAL PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bitacora inmutable de movimientos sobre cuentas institucionales del banco';

-- ============================================================================
-- 6. BLOQUEOS, HISTORIAL Y AUDITORIA
-- ============================================================================

CREATE TABLE BLOQUEO_CUENTA (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del bloqueo o retencion',
    CUENTA_ID INT NOT NULL COMMENT 'Cuenta afectada por el bloqueo',
    MONTO_BLOQUEADO DECIMAL(19,2) NOT NULL COMMENT 'Valor retenido o bloqueado',
    MOTIVO VARCHAR(100) NOT NULL COMMENT 'Motivo del bloqueo',
    AUTORIDAD_ORDENANTE VARCHAR(200) NULL COMMENT 'Autoridad u origen de la orden',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'ACTIVO o LIBERADO',
    USUARIO_CORE_ID INT NOT NULL COMMENT 'Usuario que registra el bloqueo',
    FECHA_BLOQUEO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de registro del bloqueo',
    FECHA_LIBERACION DATETIME NULL COMMENT 'Fecha de liberacion si aplica',
    OBSERVACIONES VARCHAR(300) NULL COMMENT 'Observaciones complementarias',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion del bloqueo',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para control de concurrencia optimista JPA',
    CONSTRAINT PK_BLOQUEO_CUENTA PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bloqueos o retenciones que explican el saldo disponible';

CREATE TABLE HISTORIAL_ESTADO_CUENTA (
    ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del historial de estado',
    CUENTA_ID INT NOT NULL COMMENT 'Cuenta cuyo estado cambia',
    ESTADO_ANTERIOR VARCHAR(15) NULL COMMENT 'Estado anterior de la cuenta',
    ESTADO_NUEVO VARCHAR(15) NOT NULL COMMENT 'Estado nuevo de la cuenta',
    MOTIVO_CAMBIO VARCHAR(300) NULL COMMENT 'Motivo del cambio de estado',
    USUARIO_CORE_ID INT NOT NULL COMMENT 'Usuario que ejecuta el cambio',
    FECHA_CAMBIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha del cambio',
    CONSTRAINT PK_HISTORIAL_ESTADO_CUENTA PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Trazabilidad de cambios de estado de cuenta';

CREATE TABLE AUDITORIA_EVENTO (
    ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del evento auditado',
    USUARIO_CORE_ID INT NULL COMMENT 'Usuario interno asociado si aplica',
    CREDENCIAL_WEB_ID INT NULL COMMENT 'Credencial web asociada si aplica',
    MODULO VARCHAR(50) NOT NULL COMMENT 'Modulo donde ocurre el evento',
    ACCION VARCHAR(80) NOT NULL COMMENT 'Accion ejecutada',
    ENTIDAD VARCHAR(80) NOT NULL COMMENT 'Entidad afectada',
    ENTIDAD_ID VARCHAR(80) NULL COMMENT 'Identificador de la entidad afectada',
    RESULTADO VARCHAR(20) NOT NULL DEFAULT 'EXITOSO' COMMENT 'Resultado del evento',
    CANAL_ORIGEN VARCHAR(20) NOT NULL DEFAULT 'CORE' COMMENT 'Canal origen del evento',
    IP_ORIGEN VARCHAR(45) NULL COMMENT 'Direccion IP origen si aplica',
    DETALLE_JSON LONGTEXT NULL COMMENT 'Detalle estructurado del evento en formato JSON',
    FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora del evento',
    CONSTRAINT PK_AUDITORIA_EVENTO PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria transversal de acciones criticas del Core';

-- ============================================================================
-- 7. UNIQUE CONSTRAINTS
-- ============================================================================

ALTER TABLE SUCURSAL ADD CONSTRAINT UQ_SUCURSAL_CODIGO UNIQUE (CODIGO_SUCURSAL);
ALTER TABLE SUBTIPO_CLIENTE ADD CONSTRAINT UQ_SUBTIPO_CLIENTE_CODIGO UNIQUE (CODIGO);
ALTER TABLE SUBTIPO_CLIENTE ADD CONSTRAINT UQ_SUBTIPO_CLIENTE_NOMBRE UNIQUE (NOMBRE);
ALTER TABLE SUBTIPO_CLIENTE ADD CONSTRAINT UQ_SUBTIPO_CLIENTE_ID_TIPO UNIQUE (ID, TIPO_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT UQ_CLIENTE_IDENTIFICACION UNIQUE (TIPO_IDENTIFICACION, IDENTIFICACION);
ALTER TABLE CREDENCIAL_WEB ADD CONSTRAINT UQ_CREDENCIAL_WEB_USUARIO UNIQUE (USUARIO);
ALTER TABLE USUARIO_CORE ADD CONSTRAINT UQ_USUARIO_CORE_USUARIO UNIQUE (USUARIO);
ALTER TABLE SUBTIPO_CUENTA ADD CONSTRAINT UQ_SUBTIPO_CUENTA_CODIGO UNIQUE (CODIGO);
ALTER TABLE CUENTA ADD CONSTRAINT UQ_CUENTA_NUMERO UNIQUE (NUMERO_CUENTA);
ALTER TABLE CUENTA_INSTITUCIONAL ADD CONSTRAINT UQ_CUENTA_INST_NUMERO UNIQUE (NUMERO_CUENTA);
ALTER TABLE CUENTA_INSTITUCIONAL ADD CONSTRAINT UQ_CUENTA_INST_CODIGO UNIQUE (CODIGO);
ALTER TABLE SUBTIPO_TRANSACCION ADD CONSTRAINT UQ_SUBTIPO_TRANSACCION_CODIGO UNIQUE (CODIGO);
-- Idempotencia Core RF-06: evita reprocesar la misma transaccion enviada por el Switch para la misma cuenta en el mismo dia de negocio.
ALTER TABLE TRANSACCION_CUENTA ADD CONSTRAINT UQ_TX_CUENTA_IDEMPOTENCIA UNIQUE (CUENTA_ID, UUID_TRANSACCION, FECHA_NEGOCIO);
ALTER TABLE TRANSACCION_INSTITUCIONAL ADD CONSTRAINT UQ_TX_INST_IDEMPOTENCIA UNIQUE (CUENTA_INSTITUCIONAL_ID, UUID_TRANSACCION, FECHA_NEGOCIO);

-- ============================================================================
-- 8. CHECK CONSTRAINTS
-- ============================================================================

ALTER TABLE SUCURSAL ADD CONSTRAINT CHK_SUCURSAL_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA'));
ALTER TABLE FERIADO ADD CONSTRAINT CHK_FERIADO_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));
ALTER TABLE PARAMETRO_CORE ADD CONSTRAINT CHK_PARAMETRO_TIPO_DATO CHECK (TIPO_DATO IN ('NUMERICO', 'CADENA', 'FECHA', 'HORA', 'BOOLEANO'));
ALTER TABLE SUBTIPO_CLIENTE ADD CONSTRAINT CHK_SUBTIPO_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));
ALTER TABLE SUBTIPO_CLIENTE ADD CONSTRAINT CHK_SUBTIPO_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL', 'JURIDICO'));

ALTER TABLE CLIENTE ADD CONSTRAINT CHK_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL', 'JURIDICO'));
ALTER TABLE CLIENTE ADD CONSTRAINT CHK_CLIENTE_IDENTIFICACION_TIPO CHECK (TIPO_IDENTIFICACION IN ('CEDULA', 'RUC', 'PASAPORTE'));
ALTER TABLE CLIENTE ADD CONSTRAINT CHK_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO'));
ALTER TABLE CLIENTE ADD CONSTRAINT CHK_CLIENTE_PAGOS_MASIVOS_JURIDICO CHECK (
    (TIPO_CLIENTE = 'JURIDICO') OR (ACTIVO_PAGOS_MASIVOS = 0)
);
ALTER TABLE CLIENTE ADD CONSTRAINT CHK_CLIENTE_DATOS_POR_TIPO CHECK (
    (
        TIPO_CLIENTE = 'NATURAL'
        AND TIPO_IDENTIFICACION IN ('CEDULA', 'PASAPORTE')
        AND NOMBRES IS NOT NULL
        AND APELLIDOS IS NOT NULL
        AND FECHA_NACIMIENTO IS NOT NULL
        AND RAZON_SOCIAL IS NULL
        AND FECHA_CONSTITUCION IS NULL
    )
    OR
    (
        TIPO_CLIENTE = 'JURIDICO'
        AND TIPO_IDENTIFICACION = 'RUC'
        AND RAZON_SOCIAL IS NOT NULL
        AND FECHA_CONSTITUCION IS NOT NULL
        AND REPRESENTANTE_LEGAL_ID IS NOT NULL
    )
);

ALTER TABLE CREDENCIAL_WEB ADD CONSTRAINT CHK_CREDENCIAL_WEB_ESTADO CHECK (ESTADO IN ('ACTIVO', 'BLOQUEADO', 'EXPIRADO', 'INACTIVO'));
ALTER TABLE USUARIO_CORE ADD CONSTRAINT CHK_USUARIO_CORE_ESTADO CHECK (ESTADO IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'));
ALTER TABLE USUARIO_CORE ADD CONSTRAINT CHK_USUARIO_CORE_ROL CHECK (ROL IN ('CAJERO', 'SUPERVISOR_AGENCIA', 'ADMIN_CORE', 'AUDITOR', 'SISTEMA'));

ALTER TABLE SUBTIPO_CUENTA ADD CONSTRAINT CHK_SUBTIPO_CUENTA_BASE CHECK (TIPO_BASE IN ('AHORROS', 'CORRIENTE'));
ALTER TABLE SUBTIPO_CUENTA ADD CONSTRAINT CHK_SUBTIPO_CUENTA_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE CUENTA ADD CONSTRAINT CHK_CUENTA_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA', 'SUSPENDIDA'));
ALTER TABLE CUENTA ADD CONSTRAINT CHK_CUENTA_LIMITE_SOBREGIRO CHECK (LIMITE_SOBREGIRO >= 0);
ALTER TABLE CUENTA ADD CONSTRAINT CHK_CUENTA_SALDO_CONTABLE CHECK (
    (PERMITE_SOBREGIRO = 0 AND SALDO_CONTABLE >= 0)
    OR
    (PERMITE_SOBREGIRO = 1 AND (SALDO_CONTABLE + LIMITE_SOBREGIRO) >= 0)
);
ALTER TABLE CUENTA ADD CONSTRAINT CHK_CUENTA_SALDO_DISPONIBLE CHECK (
    SALDO_DISPONIBLE <= (SALDO_CONTABLE + LIMITE_SOBREGIRO)
);

ALTER TABLE CUENTA_INSTITUCIONAL ADD CONSTRAINT CHK_CUENTA_INST_TIPO CHECK (TIPO_CUENTA IN ('INGRESO', 'PASIVO', 'IMPUESTO', 'OPERATIVA'));
ALTER TABLE CUENTA_INSTITUCIONAL ADD CONSTRAINT CHK_CUENTA_INST_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA'));

ALTER TABLE SUBTIPO_TRANSACCION ADD CONSTRAINT CHK_SUBTIPO_TX_BASE CHECK (TIPO_MOVIMIENTO_BASE IS NULL OR TIPO_MOVIMIENTO_BASE IN ('DEBITO', 'CREDITO'));
ALTER TABLE SUBTIPO_TRANSACCION ADD CONSTRAINT CHK_SUBTIPO_TX_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE TRANSACCION_CUENTA ADD CONSTRAINT CHK_TX_CUENTA_TIPO CHECK (TIPO_MOVIMIENTO IN ('DEBITO', 'CREDITO'));
ALTER TABLE TRANSACCION_CUENTA ADD CONSTRAINT CHK_TX_CUENTA_MONTO CHECK (MONTO > 0);
ALTER TABLE TRANSACCION_CUENTA ADD CONSTRAINT CHK_TX_CUENTA_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'COMPLETADA', 'RECHAZADA', 'REVERSADA'));
ALTER TABLE TRANSACCION_CUENTA ADD CONSTRAINT CHK_TX_CUENTA_CANAL CHECK (CANAL_ORIGEN IN ('CORE', 'AGENCIA', 'WEB', 'SWITCH', 'ATM', 'SISTEMA'));

ALTER TABLE TRANSACCION_INSTITUCIONAL ADD CONSTRAINT CHK_TX_INST_TIPO CHECK (TIPO_MOVIMIENTO IN ('DEBITO', 'CREDITO'));
ALTER TABLE TRANSACCION_INSTITUCIONAL ADD CONSTRAINT CHK_TX_INST_MONTO CHECK (MONTO > 0);
ALTER TABLE TRANSACCION_INSTITUCIONAL ADD CONSTRAINT CHK_TX_INST_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'COMPLETADA', 'RECHAZADA', 'REVERSADA'));
ALTER TABLE TRANSACCION_INSTITUCIONAL ADD CONSTRAINT CHK_TX_INST_CANAL CHECK (CANAL_ORIGEN IN ('CORE', 'AGENCIA', 'WEB', 'SWITCH', 'ATM', 'SISTEMA'));

ALTER TABLE BLOQUEO_CUENTA ADD CONSTRAINT CHK_BLOQUEO_MONTO CHECK (MONTO_BLOQUEADO > 0);
ALTER TABLE BLOQUEO_CUENTA ADD CONSTRAINT CHK_BLOQUEO_ESTADO CHECK (ESTADO IN ('ACTIVO', 'LIBERADO'));
ALTER TABLE BLOQUEO_CUENTA ADD CONSTRAINT CHK_BLOQUEO_FECHAS CHECK (FECHA_LIBERACION IS NULL OR FECHA_LIBERACION >= FECHA_BLOQUEO);

ALTER TABLE HISTORIAL_ESTADO_CUENTA ADD CONSTRAINT CHK_HIST_ESTADO_ANTERIOR CHECK (ESTADO_ANTERIOR IS NULL OR ESTADO_ANTERIOR IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA', 'SUSPENDIDA'));
ALTER TABLE HISTORIAL_ESTADO_CUENTA ADD CONSTRAINT CHK_HIST_ESTADO_NUEVO CHECK (ESTADO_NUEVO IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA', 'SUSPENDIDA'));

ALTER TABLE AUDITORIA_EVENTO ADD CONSTRAINT CHK_AUDITORIA_RESULTADO CHECK (RESULTADO IN ('EXITOSO', 'FALLIDO', 'RECHAZADO'));
ALTER TABLE AUDITORIA_EVENTO ADD CONSTRAINT CHK_AUDITORIA_CANAL CHECK (CANAL_ORIGEN IN ('CORE', 'AGENCIA', 'WEB', 'SWITCH', 'ATM', 'SISTEMA'));

-- ============================================================================
-- 9. FOREIGN KEYS
-- ============================================================================

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_SUBTIPO_TIPO
    FOREIGN KEY (SUBTIPO_CLIENTE_ID, TIPO_CLIENTE) REFERENCES SUBTIPO_CLIENTE(ID, TIPO_CLIENTE)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_REPRESENTANTE_LEGAL
    FOREIGN KEY (REPRESENTANTE_LEGAL_ID) REFERENCES CLIENTE(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CREDENCIAL_WEB
    ADD CONSTRAINT FK_CREDENCIAL_WEB_CLIENTE
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USUARIO_CORE
    ADD CONSTRAINT FK_USUARIO_CORE_SUCURSAL
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CUENTA
    ADD CONSTRAINT FK_CUENTA_CLIENTE
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CUENTA
    ADD CONSTRAINT FK_CUENTA_SUCURSAL
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CUENTA
    ADD CONSTRAINT FK_CUENTA_SUBTIPO
    FOREIGN KEY (SUBTIPO_CUENTA_ID) REFERENCES SUBTIPO_CUENTA(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_CUENTA
    ADD CONSTRAINT FK_TX_CUENTA_CUENTA
    FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_CUENTA
    ADD CONSTRAINT FK_TX_CUENTA_SUBTIPO
    FOREIGN KEY (SUBTIPO_TRANSACCION_ID) REFERENCES SUBTIPO_TRANSACCION(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_CUENTA
    ADD CONSTRAINT FK_TX_CUENTA_USUARIO_CORE
    FOREIGN KEY (USUARIO_CORE_ID) REFERENCES USUARIO_CORE(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_CUENTA
    ADD CONSTRAINT FK_TX_CUENTA_CREDENCIAL_WEB
    FOREIGN KEY (CREDENCIAL_WEB_ID) REFERENCES CREDENCIAL_WEB(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_INSTITUCIONAL
    ADD CONSTRAINT FK_TX_INST_CUENTA_INST
    FOREIGN KEY (CUENTA_INSTITUCIONAL_ID) REFERENCES CUENTA_INSTITUCIONAL(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_INSTITUCIONAL
    ADD CONSTRAINT FK_TX_INST_SUBTIPO
    FOREIGN KEY (SUBTIPO_TRANSACCION_ID) REFERENCES SUBTIPO_TRANSACCION(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_INSTITUCIONAL
    ADD CONSTRAINT FK_TX_INST_USUARIO_CORE
    FOREIGN KEY (USUARIO_CORE_ID) REFERENCES USUARIO_CORE(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TRANSACCION_INSTITUCIONAL
    ADD CONSTRAINT FK_TX_INST_CREDENCIAL_WEB
    FOREIGN KEY (CREDENCIAL_WEB_ID) REFERENCES CREDENCIAL_WEB(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE BLOQUEO_CUENTA
    ADD CONSTRAINT FK_BLOQUEO_CUENTA
    FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE BLOQUEO_CUENTA
    ADD CONSTRAINT FK_BLOQUEO_USUARIO_CORE
    FOREIGN KEY (USUARIO_CORE_ID) REFERENCES USUARIO_CORE(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE HISTORIAL_ESTADO_CUENTA
    ADD CONSTRAINT FK_HIST_ESTADO_CUENTA
    FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE HISTORIAL_ESTADO_CUENTA
    ADD CONSTRAINT FK_HIST_ESTADO_USUARIO_CORE
    FOREIGN KEY (USUARIO_CORE_ID) REFERENCES USUARIO_CORE(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE AUDITORIA_EVENTO
    ADD CONSTRAINT FK_AUDITORIA_USUARIO_CORE
    FOREIGN KEY (USUARIO_CORE_ID) REFERENCES USUARIO_CORE(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE AUDITORIA_EVENTO
    ADD CONSTRAINT FK_AUDITORIA_CREDENCIAL_WEB
    FOREIGN KEY (CREDENCIAL_WEB_ID) REFERENCES CREDENCIAL_WEB(ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- 10. INDICES DE RENDIMIENTO Y CONSULTA
-- ============================================================================

CREATE INDEX IDX_SUBTIPO_CLIENTE_TIPO_ESTADO_NOMBRE ON SUBTIPO_CLIENTE(TIPO_CLIENTE, ESTADO, NOMBRE);
CREATE INDEX IDX_CLIENTE_SUBTIPO ON CLIENTE(SUBTIPO_CLIENTE_ID);
CREATE INDEX IDX_CLIENTE_ESTADO ON CLIENTE(ESTADO);
CREATE INDEX IDX_CLIENTE_PAGOS_MASIVOS ON CLIENTE(TIPO_CLIENTE, TIPO_IDENTIFICACION, IDENTIFICACION, ACTIVO_PAGOS_MASIVOS, ESTADO);
CREATE INDEX IDX_CLIENTE_REP_LEGAL ON CLIENTE(REPRESENTANTE_LEGAL_ID);
CREATE INDEX IDX_CREDENCIAL_CLIENTE ON CREDENCIAL_WEB(CLIENTE_ID);
CREATE INDEX IDX_USUARIO_SUCURSAL ON USUARIO_CORE(SUCURSAL_ID);

CREATE INDEX IDX_CUENTA_CLIENTE ON CUENTA(CLIENTE_ID);
CREATE INDEX IDX_CUENTA_SUCURSAL ON CUENTA(SUCURSAL_ID);
CREATE INDEX IDX_CUENTA_SUBTIPO ON CUENTA(SUBTIPO_CUENTA_ID);
CREATE INDEX IDX_CUENTA_ESTADO ON CUENTA(ESTADO);
CREATE INDEX IDX_CUENTA_FAVORITA ON CUENTA(CLIENTE_ID, ES_FAVORITA_PAGOS);

CREATE INDEX IDX_TX_CUENTA_FECHA ON TRANSACCION_CUENTA(CUENTA_ID, FECHA_TRANSACCION);
CREATE INDEX IDX_TX_CUENTA_NEGOCIO ON TRANSACCION_CUENTA(CUENTA_ID, FECHA_NEGOCIO);
CREATE INDEX IDX_TX_CUENTA_CANAL ON TRANSACCION_CUENTA(CANAL_ORIGEN, FECHA_TRANSACCION);
CREATE INDEX IDX_TX_CUENTA_GRUPO ON TRANSACCION_CUENTA(UUID_GRUPO_OPERACION);
CREATE INDEX IDX_TX_CUENTA_REFERENCIA ON TRANSACCION_CUENTA(REFERENCIA_EXTERNA);

CREATE INDEX IDX_TX_INST_FECHA ON TRANSACCION_INSTITUCIONAL(CUENTA_INSTITUCIONAL_ID, FECHA_TRANSACCION);
CREATE INDEX IDX_TX_INST_GRUPO ON TRANSACCION_INSTITUCIONAL(UUID_GRUPO_OPERACION);
CREATE INDEX IDX_TX_INST_REFERENCIA ON TRANSACCION_INSTITUCIONAL(REFERENCIA_EXTERNA);

CREATE INDEX IDX_BLOQUEO_CUENTA_ESTADO ON BLOQUEO_CUENTA(CUENTA_ID, ESTADO);
CREATE INDEX IDX_HIST_ESTADO_CUENTA_FECHA ON HISTORIAL_ESTADO_CUENTA(CUENTA_ID, FECHA_CAMBIO);
CREATE INDEX IDX_AUDITORIA_FECHA ON AUDITORIA_EVENTO(FECHA_EVENTO);
CREATE INDEX IDX_AUDITORIA_ENTIDAD ON AUDITORIA_EVENTO(ENTIDAD, ENTIDAD_ID);
CREATE INDEX IDX_AUDITORIA_MODULO ON AUDITORIA_EVENTO(MODULO, ACCION);

-- ============================================================================
-- 11. DATOS BASE MINIMOS OPCIONALES
--     Pueden comentarse si PowerDesigner solo se usara para ingenieria inversa.
-- ============================================================================

INSERT INTO PARAMETRO_CORE (CODIGO, NOMBRE, VALOR_TEXTO, TIPO_DATO, DESCRIPCION) VALUES
('IVA_PORCENTAJE', 'Porcentaje de IVA vigente', '0.15', 'NUMERICO', 'Parametro usado por el Switch para liquidacion de comisiones'),
('HORA_CORTE_PAGOS_MASIVOS', 'Hora de corte pagos masivos', '18:00:00', 'HORA', 'Hora limite para procesamiento inmediato de lotes'),
('MONEDA_BASE', 'Moneda base operativa', 'USD', 'CADENA', 'Moneda principal de operacion del Core');

INSERT INTO SUBTIPO_CLIENTE (TIPO_CLIENTE, CODIGO, NOMBRE, DESCRIPCION) VALUES
('NATURAL', 'NAT_MASIVO', 'Natural Masivo', 'Cliente natural de banca masiva'),
('NATURAL', 'NAT_ALTO_VALOR', 'Natural Alto Valor', 'Cliente natural preferente'),
('JURIDICO', 'JUR_PYME', 'PyME', 'Cliente juridico pequena o mediana empresa'),
('JURIDICO', 'JUR_CORPORATIVO', 'Corporativo', 'Cliente juridico corporativo');

INSERT INTO SUBTIPO_CUENTA (TIPO_BASE, CODIGO, NOMBRE, DESCRIPCION) VALUES
('AHORROS', 'AHO_STD', 'Cuenta de Ahorros', 'Producto de ahorro estandar'),
('CORRIENTE', 'CTE_STD', 'Cuenta Corriente', 'Producto corriente estandar'),
('AHORROS', 'NOM_STD', 'Cuenta Nomina', 'Producto usado para abonos de nomina');

INSERT INTO SUBTIPO_TRANSACCION (CODIGO, NOMBRE, TIPO_MOVIMIENTO_BASE) VALUES
('PAGO_MASIVO', 'Pago masivo', 'DEBITO'),
('ABONO_NOMINA', 'Abono de nomina', 'CREDITO'),
('DEPOSITO_VENTANILLA', 'Deposito por ventanilla', 'CREDITO'),
('RETIRO_CAJERO', 'Retiro por cajero', 'DEBITO'),
('COMPRA_COMERCIO', 'Compra en comercio', 'DEBITO'),
('COBRO_COMISION', 'Cobro de comision', 'DEBITO'),
('PAGO_IMPUESTO', 'Pago de impuesto', 'DEBITO'),
('TRANSFERENCIA_RECIBIDA', 'Transferencia recibida', 'CREDITO'),
('TRANSFERENCIA_SALIDA', 'Transferencia salida', 'DEBITO'),
('INGRESO_SERVICIO_MASIVO', 'Ingreso por servicio de pagos masivos', 'CREDITO'),
('IVA_SERVICIO_MASIVO', 'IVA por servicio de pagos masivos', 'CREDITO'),
('REVERSO', 'Reverso operativo', NULL);

INSERT INTO CUENTA_INSTITUCIONAL (NUMERO_CUENTA, CODIGO, NOMBRE, TIPO_CUENTA) VALUES
('9000000001', 'INGRESOS_SERVICIOS_MASIVOS', 'Ingresos por servicios de pagos masivos', 'INGRESO'),
('9000000002', 'PASIVOS_IVA_RETENIDO', 'Pasivos por IVA retenido/cobrado', 'PASIVO');

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================
