package com.banquito.core.security.enums;

import lombok.Getter;

@Getter
public enum PermisoEnum {
    // Permisos para USUARIO_CORE
    USUARIO_CORE_LEER("USUARIO_CORE_LEER"),
    USUARIO_CORE_CREAR("USUARIO_CORE_CREAR"),
    USUARIO_CORE_ACTUALIZAR("USUARIO_CORE_ACTUALIZAR"),
    USUARIO_CORE_ELIMINAR("USUARIO_CORE_ELIMINAR"),

    // Permisos para SUBTIPO_TRANSACCION
    SUBTIPO_TRANSACCION_LEER("SUBTIPO_TRANSACCION_LEER"),
    SUBTIPO_TRANSACCION_CREAR("SUBTIPO_TRANSACCION_CREAR"),
    SUBTIPO_TRANSACCION_ACTUALIZAR("SUBTIPO_TRANSACCION_ACTUALIZAR"),
    SUBTIPO_TRANSACCION_ELIMINAR("SUBTIPO_TRANSACCION_ELIMINAR"),

    // Permisos para TRANSACCION_CUENTA
    TRANSACCION_CUENTA_LEER("TRANSACCION_CUENTA_LEER"),
    TRANSACCION_CUENTA_CREAR("TRANSACCION_CUENTA_CREAR"),
    TRANSACCION_CUENTA_ACTUALIZAR("TRANSACCION_CUENTA_ACTUALIZAR"),
    TRANSACCION_CUENTA_ELIMINAR("TRANSACCION_CUENTA_ELIMINAR"),

    // Permisos para CUENTA
    CUENTA_LEER("CUENTA_LEER"),
    CUENTA_CREAR("CUENTA_CREAR"),
    CUENTA_ACTUALIZAR("CUENTA_ACTUALIZAR"),
    CUENTA_ELIMINAR("CUENTA_ELIMINAR"),
    CUENTA_CAMBIAR_ESTADO("CUENTA_CAMBIAR_ESTADO"),

    // Permisos para CLIENTE
    CLIENTE_LEER("CLIENTE_LEER"),
    CLIENTE_CREAR("CLIENTE_CREAR"),
    CLIENTE_ACTUALIZAR("CLIENTE_ACTUALIZAR"),
    CLIENTE_ELIMINAR("CLIENTE_ELIMINAR"),
    CLIENTE_CAMBIAR_ESTADO("CLIENTE_CAMBIAR_ESTADO"),

    // Permisos para AUDITORIA_EVENTO
    AUDITORIA_LEER("AUDITORIA_LEER"),

    // Permisos especiales
    TRANSACCION_OVERRIDE("TRANSACCION_OVERRIDE"),
    TRANSACCION_APROBAR_MONTO_ALTO("TRANSACCION_APROBAR_MONTO_ALTO");

    private final String value;

    PermisoEnum(String value) {
        this.value = value;
    }
}
